#!/usr/bin/env bash
# Sets up a Zitadel playground.
#
# Assumes DNS/TLS can be set up according to: https://github.com/jonesinator/macos-dev-setup/
#
# Dependencies:
#   brew install colima docker helm jq kubectl opentofu
set -euo pipefail

# Can run multiple instances by changing profile. (NOT WELL TESTED)
: "${colima_profile:=default}"

# Can change the top-level URL. (NOT WELL TESTED)
: "${base_address:=example.tld}"

# Remove any existing data.
rm -rf zitadel-admin-sa.json terraform.tfstate* .terraform ./zitadel.auto.tfvars
colima delete --force --profile "${colima_profile}" || true

# Set up a new instance of colima with Kubernetes including Traefik ingress.
colima start \
  --cpu 4 \
  --k3s-arg= \
  --kubernetes \
  --memory 8 \
  --network-address \
  --profile "${colima_profile}" \
  --vm-type vz
colima_ip="$(colima status --json --profile "${colima_profile}" |
  jq --exit-status --raw-output .ip_address)"

# Configure DNS to point the base address and all subdomains to the colima IP. If this conflicts
# with another file you're going to have a bad time. That is not automatically detected.
mkdir -p ~/.local/share/dns
cat << EOF > "${HOME}/.local/share/dns/colima-${colima_profile}.conf"
local-zone: "${base_address}." redirect
local-data: "${base_address}. IN A ${colima_ip}"
EOF
sudo brew services restart unbound
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder

# Set up cert-manager and create a certificate issuer using the already-trusted root certificate on
# the system.
helm repo add jetstack https://charts.jetstack.io --force-update
helm upgrade cert-manager jetstack/cert-manager \
  --create-namespace \
  --install \
  --namespace cert-manager \
  --set crds.enabled=true \
  --version v1.16.2
kubectl create secret tls root-ca-secret --namespace cert-manager \
  --cert="${HOME}/.local/share/ca/root.pem" --key="${HOME}/.local/share/ca/root-key.pem"
kubectl apply -f - << EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: root-ca-secret
EOF

# Deploy MailHog. This allows testing email locally.
mailhog_address="mail.${base_address}"
helm repo add codecentric https://codecentric.github.io/helm-charts
helm install mailhog codecentric/mailhog
kubectl apply -f - << EOF
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-certificate
spec:
  commonName: ${mailhog_address}
  dnsNames:
    - ${mailhog_address}
  secretName: mail-certificate-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mail-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(\`${mailhog_address}\`)
      kind: Rule
      services:
        - name: mailhog
          port: 8025
  tls:
    secretName: mail-certificate-secret
EOF

# Deploy cockroachdb, for zitadel.
helm repo add cockroachdb https://charts.cockroachdb.com
helm upgrade db cockroachdb/cockroachdb --install --version 15.0.3 --set tls.enabled=false

# Deploy zitadel.
zitadel_address="id.${base_address}"
helm repo add zitadel https://charts.zitadel.com
helm upgrade --install zitadel zitadel/zitadel -f - << EOF
zitadel:
  masterkey: $(openssl rand -hex 16)
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: ${zitadel_address}
    TLS:
      Enabled: false
    Database:
      Cockroach:
        Host: db-cockroachdb-public
    FirstInstance:
      Org:
        Machine:
          Machine:
            Username: zitadel-admin-sa
            Name: Admin
          MachineKey:
            ExpirationDate: "2026-01-01T00:00:00Z"
            Type: 1
EOF
kubectl apply -f - << EOF
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: id-certificate
spec:
  commonName: ${zitadel_address}
  dnsNames:
    - ${zitadel_address}
  secretName: id-certificate-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: id-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(\`${zitadel_address}\`)
      kind: Rule
      services:
        - name: zitadel
          port: 8080
          scheme: h2c
          passHostHeader: true
  tls:
    secretName: id-certificate-secret
EOF

# Configure Zitadel using OpenTofu.
kubectl -n default get secret zitadel-admin-sa -o jsonpath='{ .data.zitadel-admin-sa\.json }' |
  base64 -D > zitadel-admin-sa.json
cat << EOF >> zitadel.auto.tfvars
zitadel_address = "${zitadel_address}"
redirect_address = "app.${base_address}"
EOF
tofu init
tofu apply -auto-approve

# Show the local URLs that can be used to connect to the services.
echo
echo "Zitadel: https://${zitadel_address}"
echo "  Username: zitadel-admin@zitadel.${zitadel_address}"
echo "  Password: Password1!"
echo "MailHog: https://${mailhog_address}"
echo
